version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Karm/serve-file
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: curl https://glide.sh/get | sh
      - run: glide install
      - run: go get github.com/jstemmer/go-junit-report 
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:  
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results